project:
  type: website

website:
  # logo: logo.png
  favicon: logo.png
  site-url: https://www.nipskateboards.github.io
  title: "Nip Skate Company"
  navbar:
    tools:
      - icon: github
        href: https://github.com/nipskateboards
        menu:
        - file: about.qmd
          text: Contact

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



